### ISSUE TITLE
Facebook Notifcations No Poster

### ISSUE THREAD

**Issue by AaronSadlerUK** [Tautulli/Tautulli#1038]
**Version:**
1.4.18
**Branch:**
master
**Commit hash:**

**Operating system:**
CentOS 7
**Python version:**
2.7.5
**What you did?**
Added a film to Plex
**What happened?**
Facebook notification should have included the poster but it didn't.
It did upload it to Imgur though
**What you expected?**
The poster to be included in the Facebook post

As you can see from the screenshot i even tried to include the url to the poster in one of the posts with no luck

And the checkbox is ticked to include the poster
![2017-05-23](https://cloud.githubusercontent.com/assets/9937803/26375682/cd44816a-4001-11e7-8057-2b4d24d511dc.png)

**Comment by alneven** [comment]
I have this issue as well
The upload is working, but there is no IMAGE in the post.

> PlexPy Helpers :: Image 'Best of the Best' uploaded to Imgur.

I have two servers, identical setup, the first (old) is working, the new (since February) it's not.
I have to publishing apps in DEV Facebook.
All settings are the same.
But I think is because the new publishing app is somehow defect:

> Misconfigured App
> Sorry, PlexPy-XXX hasn't been approved for display in App Center.

It's "live" under "App review"
Even if I change it to development and back to live
No posts with image. :-(

![screen shot 2017-06-24 at 13 11 06](https://user-images.githubusercontent.com/16620485/27508114-ebbd662a-58de-11e7-9dff-98684a9b798d.png)


PlexPy Version: 1.4.19
Python Version: 2.7.12

**Comment by JonnyWong16** [comment]
I'm unable to reproduce the issue.

![image](https://user-images.githubusercontent.com/9099342/27510527-67b5e774-58c7-11e7-95e2-2342b5982fa9.png)

**Comment by alneven** [comment]
after my post I've created a new "app" on fb dev
and the same
no poster
;-(

only the post
the link itself doesn't include the image

nothing shows up in the logs

**Comment by alneven** [comment]
hint:
the same setup for Telegram is working

**Comment by JonnyWong16** [comment]
I said I cannot reproduce the issue. I tried looking for the issue and I didn't see anything wrong. Until either you, me, or someone else can figure out why and let me know, there is really nothing I can do about it. My best guess right now is that it's an issue on Facebook's side.

**Comment by alneven** [comment]
so, I have fixed it...

as for my facebook APP for my old server this IMAGE/POSTER function is OK
I have added the URL from my new server to the "Valid OAuth redirect URIs" in the old facebook APP
and requested the authorisation

now it's working:
![screen shot 2017-06-26 at 21 38 32](https://user-images.githubusercontent.com/16620485/27556911-e5f5e1c4-5ab7-11e7-9d7b-312312e011d8.png)

**Comment by JonnyWong16** [comment]
Thanks for the update.

**Comment by seanism** [comment]
I am still having this issue.  I've confirmed everything and it is uploading the images.

<img width="519" alt="screen shot 2017-07-06 at 8 46 31 pm" src="https://user-images.githubusercontent.com/10472025/27942552-936b29aa-628c-11e7-875e-4e1918b1a5b6.png">
<img width="504" alt="screen shot 2017-07-06 at 8 37 16 pm" src="https://user-images.githubusercontent.com/10472025/27942553-936b6ece-628c-11e7-92d0-4364d95c16dc.png">

**Comment by cubz90** [comment]
It appears this action has been deprecated by Facebook in the newest API. These will also stop working for older API's on 17th July 2017.

https://developers.facebook.com/docs/sharing/reference/feed-dialog#deprecated-params

**Comment by crazyman143** [comment]
Is there any way to remove thetvdb.com link from the posts? I'd rather have nothing than the picture of their logo on every post. Can seem to find a way to disable it?

**Comment by alneven** [comment]
so, now the problem is back... nothing changed

```PlexPy Helpers :: Image 'The Impossible' uploaded to Imgur.```

![plexpy](https://user-images.githubusercontent.com/16620485/28360878-0e77a788-6c77-11e7-8962-b3fc1ee67092.png)




@JonnyWong16 
plexpy has to be updated, or something?!

**Comment by alneven** [comment]
update:
I see there is no option :-(

https://github.com/JonnyWong16/plexpy/issues/1063

**Comment by thegreyfox** [comment]
If you try without linking back to Plex, the image shows up.

**Comment by cubz90** [comment]
Only for movies as it grabs the image from. IMDB. Doesn't for tv shows as
it grabs the image from the banner on TheTVDB.

**Comment by jeff15110168** [comment]
so this is permanently lost feature until facebook adds it back..?

**Comment by cubz90** [comment]
Facebook won't be adding it back. But yes, its permanent.

**Comment by spuniun** [comment]
I added a feature request to TheTVDB to add OG tags so it works like IMDb
https://forums.thetvdb.com/viewtopic.php?f=5&t=38707

**Comment by cubz90** [comment]
Hopefully they'll oblige
