### ISSUE TITLE
When Users are deleted from Plex, they are not deleted from PlexPy

### ISSUE THREAD

**Issue by zenjabba** [Tautulli/Tautulli#115]
Deleted 50 users from Plex, those users not deleted from PlexPy, even after requesting "refresh users"

**Comment by JonnyWong16** [comment]
The deletion of users should not be automatic with "Refresh users". Some people might want to keep data from users removed from Plex.

With that being said, implementing a separate "Refresh and delete users" function could be done.

**Comment by drzoidberg33** [comment]
Exactly what JW said.

You can use the purge option in the user edit screen to remove history items (although the user names will still show in the user list).

**Comment by JonnyWong16** [comment]
I think the purge option on the user edit screen is broken, but I just implemented group purging in #118. Just purging history, not deleting users.

**Comment by drzoidberg33** [comment]
@JonnyWong16 What exactly is broken? I tested it quite a few times and worked. Tested it now again and works - so some more detail would be helpful.

**Comment by JonnyWong16** [comment]
@drzoidberg33 It could just be me. The javascript confirm function doesn't work for me in Chrome. Maybe I have something blocking it? It works in other browsers.

I might change it to use the bootstrap modal confirm box, like the one I implemented on the users table. It's prettier. =P

**Comment by drzoidberg33** [comment]
That's weird. I use Chrome primarily and haven't had issues. The bootstrap modal is a lot prettier, so go ahead :smile:

**Comment by zenjabba** [comment]
I've tried to use this function, but the purge function doesn't do anything (tried in Safari and Chrome). The Logs are showing deletion taking place, when the "All Users" screen is still showing the users.

2015-08-30 23:21:25 INFO    PlexPy DataFactory :: Deleting all history for user id 4551217 from database.
2015-08-30 23:21:25 INFO    PlexPy DataFactory :: Deleting all history for user id 4544296 from database.
2015-08-30 23:21:25 INFO    PlexPy DataFactory :: Deleting all history for user id 4419732 from database.

![screenshot 2015-08-30 23 26 56](https://cloud.githubusercontent.com/assets/679864/9571644/a07c38e2-4f6e-11e5-9c7b-db6f6d57e889.png)

**Comment by drzoidberg33** [comment]
@zenjabba As mentioned in this very issue, the purge option only removes history for the user, it does not delete the actual user's entry. According to the screenshot above it looks like it's working exactly how it is intended to work.

**Comment by JonnyWong16** [comment]
Delete users added in v1.2.8
