### ISSUE TITLE
Issues Running beta on MacOS

### ISSUE THREAD

**Issue by Mark7even** [Tautulli/Tautulli#1187]
**Version:**

v2.0.7

**Branch:**

Beta

**Commit hash:**

**Operating system:**

Mac OS High Sierra 10.13.2

**Python version:**

**What you did?**

Unzipped, Python Plexpy.py at the directory.

**What happened?**
```  File "PlexPy.py", line 35, in <module>
    import plexpy
  File "/Applications/plexpy-beta/plexpy/__init__.py", line 35, in <module>
    import activity_handler
  File "/Applications/plexpy-beta/plexpy/activity_handler.py", line 24, in <module>
    import activity_processor
  File "/Applications/plexpy-beta/plexpy/activity_processor.py", line 23, in <module>
    import database
  File "/Applications/plexpy-beta/plexpy/database.py", line 24, in <module>
    import logger
  File "/Applications/plexpy-beta/plexpy/logger.py", line 30, in <module>
    import helpers
  File "/Applications/plexpy-beta/plexpy/helpers.py", line 41, in <module>
    import request
  File "/Applications/plexpy-beta/plexpy/request.py", line 21, in <module>
    import requests
  File "lib/requests/__init__.py", line 98, in <module>
    from . import packages
  File "lib/requests/packages.py", line 7, in <module>
    locals()[package] = __import__(package)
ImportError: No module named idna
```
**What you expected?**

**How can we reproduce your issue?**

Unzipped, Python Plexpy.py at the directory.

**What are your (relevant) settings?**

**Link to logs:**

**Comment by creoden** [comment]
Getting the same error since updating, had to roll back to the previous version.

**Comment by JonnyWong16** [comment]
This was fixed in some version of the beta, but I don't remember which one now.

**Comment by Mark7even** [comment]
Still not working.

New error is : "500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request."

`2018-01-20 20:22:11 - INFO :: MainThread : Checking if the database upgrades are required...
2018-01-20 20:22:11 - DEBUG :: MainThread : Altering database. Updating database table notify_log.
2018-01-20 20:22:11 - DEBUG :: MainThread : User 'Local' does not exist. Adding user.
2018-01-20 20:22:11 - INFO :: MainThread : Checking if configuration upgrades are required...
2018-01-20 20:22:11 - INFO :: MainThread : Tautulli Notifiers :: Upgrading to new notification system...
2018-01-20 20:22:11 - INFO :: MainThread : Tautulli Config :: Writing configuration to file
2018-01-20 20:22:11 - INFO :: MainThread : Tautulli Libraries :: Upgrading library notification toggles...
2018-01-20 20:22:11 - INFO :: MainThread : Tautulli Config :: Writing configuration to file
2018-01-20 20:22:11 - DEBUG :: MainThread : Generating UUID...
2018-01-20 20:22:11 - INFO :: MainThread : Tautulli Config :: Writing configuration to file
2018-01-20 20:22:11 - DEBUG :: MainThread : Generating API key...
2018-01-20 20:22:11 - INFO :: MainThread : Tautulli Config :: Writing configuration to file
2018-01-20 20:22:11 - DEBUG :: MainThread : Generating JWT secret...
2018-01-20 20:22:11 - INFO :: MainThread : Tautulli Config :: Writing configuration to file
2018-01-20 20:22:11 - INFO :: MainThread : Retrieving latest version information from GitHub
2018-01-20 20:22:11 - DEBUG :: MainThread : Requesting URL via GET method: https://api.github.com/repos/JonnyWong16/plexpy/commits/master
2018-01-20 20:22:11 - DEBUG :: MainThread : Latest version is cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca
2018-01-20 20:22:11 - INFO :: MainThread : You are running an unknown version of Tautulli. Run the updater to identify your version
2018-01-20 20:22:11 - INFO :: MainThread : Tautulli NotificationHandler :: Starting background notification handler (2 threads).
2018-01-20 20:22:11 - INFO :: MainThread : Tautulli WebStart :: Starting Tautulli web server on http://0.0.0.0:8181/`

**Comment by JonnyWong16** [comment]
Participation in the beta requires installing via git.

**Comment by Mark7even** [comment]
Does the Git clone need a specific flag to specify the beta branch is
what's wanted? git clone https://github.com/JonnyWong16/plexpy.git?

**Comment by Arcanemagus** [comment]
@Mark7even the [installation instructions](https://github.com/JonnyWong16/plexpy/wiki/Installation#mac-osx) combined with the [beta announcement post](https://www.reddit.com/r/PleX/comments/7kmhl3/its_finally_here_tautulli_v2_beta_formerly_plexpy/) should clarify how you can get this installed.
