### ISSUE TITLE
get_library_media_info api outputs wrong media_type for type photo_album

### ISSUE THREAD

**Issue by tfonfara** [Tautulli/Tautulli#1238]
**Version:** v2.0.16-beta
**Branch:** beta
**Commit hash:** d15223fb1af4e86297fbfed355f537822ec82f3e
**Operating system:** Linux 4.4.0-112-generic
**Python version:** 2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]
**What you did?** Called get_library_media_info with section id of photo section as described in the [docs](https://github.com/JonnyWong16/plexpy/blob/beta/API.md)
**What happened?** Got media_type == "photo" for photo albums
**What you expected?** Expected media_type == "photo_album"
**How can we reproduce your issue?**

1. Call api with a section id that is of type "photo": `https://<host>/api/v2?apikey=<apikey>&cmd=get_library_media_info&section_id=<photo_section_id>`
2. Api result shows media_type "photo" instead of "photo_album" for albums
3. Verify the media_type by calling metadata api with the rating key from one of the albums `https://<host>/api/v2?apikey=<apikey>&cmd=get_metadata&rating_key=<rating_key_from_step_1>`
4. Api result shows media_type "photo_album" as expected

**Comment by JonnyWong16** [comment]
Fixed in v2.0.17-beta.

**Comment by tfonfara** [comment]
@JonnyWong16 just updated to the v2.0.17-beta but still get mediaType photos for albums while get_metadata shows photo_album. Also did a library refresh. Do I have to clear any other caches?

**Comment by JonnyWong16** [comment]
You have to clear the `media_info_X.json` file in the cache directory.

**Comment by tfonfara** [comment]
👍 that fixed it. Thanks!
