### ISSUE TITLE
get_library_media_info no longer able to sort by 'title' field

### ISSUE THREAD

**Issue by triantos** [Tautulli/Tautulli#1240]
**Version:**
v2.0.16 beta

**Branch:**
beta

**Commit hash:**
d15223fb1af4e86297fbfed355f537822ec82f3e

**Operating system:**
Ubuntu Linux 16.04

**Python version:**
2.7.12

**What you did?**
Called get_library_media_info API call

**What happened?**
Error in log: Tautulli APIv2 :: Failed to run get_library_media_info with {'order_column': u'title', 'order_dir': u'asc', 'section_type': u'movie', 'section_id': u'1', 'start': u'0', 'length': u'25', 'rating_key': u'0'}: u'title' is not in list

**What you expected?**
List of return values that includes title

**How can we reproduce your issue?**

Make an API call for get_library_media_info that includes optional param 'order_column': u'title'

**What are your (relevant) settings?**
Unknown

**Link to logs:**
n/a

This used to work in PlexPy (unsure what version I was running). Since I cut over to Tautulli my code no longer works. Happy to send the whole (short) python script if that's of use. It scans a library and looks for non-H.264-encoded videos.

**Comment by triantos** [comment]
OK when I skip the order_column param I get output: {u'response': {u'message': None, u'data': {u'recordsFiltered': 0, u'recordsTotal': 0, u'draw': 0, u'data': u'null', u'error': u'Unable to execute database query.'}, u'result': u'success'}}. I think somehow I'm failing in allow_session_library() but I don't understand why. My API key still seems correct. Is there some new setting I'd need to enable?

**Comment by triantos** [comment]
OK it looks like for some reason in get_library_media_info() 'title' is being aliased to "sort_title". Do I need to update my database or do something else to make this work? And at minimum, in webserve.py, function get_library_media_info(), it looks like at line 4910 after the # Alias 'title' to 'sort_title' comment, you're using a double equal sign when you should be using a single one to assign kwargs['order_column'] = 'sort_title'.

**Comment by JonnyWong16** [comment]
3c811009578a96224d6f7e9ab2a727de61d88c92

**Comment by JonnyWong16** [comment]
Fixed in v2.0.17-beta.

**Comment by triantos** [comment]
Thanks Jonny it does look like those are good fixes but I'm still getting `Tautulli APIv2 :: Failed to run get_library_media_info with {'order_column': u'title', 'order_dir': u'asc', 'section_type': u'movie', 'section_id': u'1', 'start': u'0', 'length': u'25'}: 'sort_title'`

I'm attaching the small script that I use to check which movies are in old formats (MPEG2, AVI containers, etc.). I used to be able to run this but now it fails. Do you see the same?

[movlibupgrade.py.txt](https://github.com/JonnyWong16/plexpy/files/1692041/movlibupgrade.py.txt)

**Comment by JonnyWong16** [comment]
Have you cleared your `media_info_X.json` cache files?

**Comment by triantos** [comment]
Cool that was it, again thanks for the super fast replies and for making such a great tool!
