### ISSUE TITLE
127.0.0.1 is classified as an external ip

### ISSUE THREAD

**Issue by haboutnnah** [Tautulli/Tautulli#668]
![Proof](http://i.imgur.com/rg8bKoO.png)

**Comment by tf2manu994** [comment]
[](http://i.imgur.com/rg8bKoO.png)

**Comment by JonnyWong16** [comment]
Please read the [guidelines](https://github.com/drzoidberg33/plexpy#issues).

Closing since no info provided. Reopen when you provide more details.

**Comment by haboutnnah** [comment]
It's not an error. It just detects 127.0.0.1 as external. Logs wouldn't help.

**Comment by JonnyWong16** [comment]
I commented before you edited your post with a screenshot.

**Comment by haboutnnah** [comment]
I edited my post before you commented. Probably as you were typing.

**Comment by JonnyWong16** [comment]
Fixed in v1.3.15.

**Comment by dbotamous** [comment]
I'm still having this issue on version 1.4.5, should I open a new issue? 
My PlexPy is installed on my Plex Server, it is running Ubuntu Server 14.04 with no gui. There is no way it could be coming from 127.0.0.1
![ips](https://cloud.githubusercontent.com/assets/2225569/15919883/bb8b5f6c-2dd2-11e6-8963-fdf2372323e5.PNG)
