### ISSUE TITLE
plexwatch import error

### ISSUE THREAD

**Issue by kmpanilla** [Tautulli/Tautulli#815]
Having an issue importing my plexWatch db. 
plexWatch version is: #  Version: 0.3.3-DEV

**Version:** 1.4.10

**Branch:**  master

**Commit hash:**  2a701a6dfea6ef4abda0c6db5f23f59d2a251a35

**Operating system:**  CentOS-7.2.1511 64bit

**Python version:**  2.7.5 (default, Nov 20 2015, 02:00:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

**What you did?**  Tired to import from /opt/plexWatch/plexWatch.db from the web. 

**What happened?**  traceback error. 

**What you expected?** the import to happen :)

**How can we reproduce your issue?**  I can provide link to db, just let me know.

**What are your (relevant) settings?**

**Link to logs:**   http://pastebin.com/mYgJj5Xi

**Comment by JonnyWong16** [comment]
I messed up. Thanks for letting me know.

**Comment by MDamon** [comment]
I'm experiencing a similar issue on import running on ubuntu.. Can you recommend any work arounds?  Thanks! Great app.. so glad to be done with plexwatch

**Comment by JonnyWong16** [comment]
You can try going back to v1.4.8, import your PlexWatch database, then upgrade to v1.4.10 again. Or wait for the bug to be fixed in the next release.

---

To go back to any previous version, shut down PlexPy and run from the command line

```
git checkout v1.4.8
```

**Comment by Pyhrra** [comment]
Reversal to V1.4.8 and import was successful. 
Upgrade to V1.4.10 and all is good.

What is causing the database import issue in V1.4.10 ?

**Comment by JonnyWong16** [comment]
I made a mistake.

**Comment by henkjanvries** [comment]
is there a way to downgrade on synology? im experiencing import problems as well.
db vs: 0.3.2
plexpy: 1.4.10

**Comment by JonnyWong16** [comment]
Fixed in v1.4.11.

**Comment by henkjanvries** [comment]
Upgraded to 1.4.11 on synology, still getting error: PlexPy Importer :: Invalid database specified.
Copied filepath to field, cant drag the file to the pathfield.

**Comment by JonnyWong16** [comment]
Are you sure you have the correct database file? And PlexPy can access that database?

You should be entering `/path/to/plexwatch.db`.

**Comment by henkjanvries** [comment]
that is what im trying to do.
path is /Users/username/Downloads/plexWatch.db
<img width="407" alt="schermafbeelding 2016-09-09 om 00 14 23" src="https://cloud.githubusercontent.com/assets/737006/18368860/7a0eebe2-7622-11e6-8ddb-11d2184b9e13.png">

**Comment by JonnyWong16** [comment]
Can PlexPy access that file though? If you are using dockers or something like that, you need to share the folder between your docker containers.

**Comment by henkjanvries** [comment]
im really sorry, when you said, can he access it, a lightbulb starting flashing. Plexpy needs to import from a synology location. I thought a location from my mac..

Its importing as we speak! thanks.

**Comment by RobM83** [comment]
A bit late to the game, but I just found out that it is also important, that the plexWatch.db is placed in folder with RW rights.
